name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight&hide_border=true&include_all_commits=true&count_private=true
          path: profile/stats.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&theme=tokyonight&hide_border=true&langs_count=8
          path: profile/top-langs.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate isometric calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: schembriaiden
          template: classic
          base: ""
          config_timezone: Europe/Malta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: profile/isocalendar.svg
          output_action: none

      - name: Generate starred repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: schembriaiden
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
          filename: profile/starred-repos.svg
          output_action: none

      - name: Generate Profile Trophy
        uses: ryo-ma/github-profile-trophy@master
        with:
            token: ${{ secrets.GH_PAT }}
            username: schembriaiden
            output_path: profile/trophy.svg

      - name: Move metrics files and commit
        run: |
          sudo mv /metrics_renders/profile/* ./profile/
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push